Repository corso-android-ivan-morgillo/team-c, pull requests merged in 2021-02, with the labels that each got.

#1 chore: Update junit
  app/build.gradle
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MainActivity.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MainViewModel.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MyApplication.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/RecipesAdapter.kt
Labels: chore

#2 chore : fix detekt and sonarLint warnings
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MainActivity.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MainViewModel.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MyApplication.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/RecipesAdapter.kt
  app/src/main/res/layout/activity_main.xml
Labels: chore

#3 feat: added val recipeList using fun rangeTo and map
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MainViewModel.kt
Labels: chore

#4 feat: recipe_list
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MainViewModel.kt
Labels: feat

#7 chore/adddetekttoci
  .github/workflows/android.yml
  app/build.gradle
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MainViewModel.kt
  build.gradle
  config/detekt.yml
Labels: chore

#19 Feat/viewmodel activity comunication
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MainActivity.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MainViewModel.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/RecipesAdapter.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/SingleLiveEvent.java
  app/src/main/res/layout/recipe_item.xml
Labels: feat

#30 chore/ExtractKoinModule
  app/build.gradle
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/KoinModule.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MyApplication.kt
Labels: chore

#31 feat/added_Retrofit
  app/build.gradle
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/KoinModule.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MyApplication.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/RecipesRepository.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/network/RecipeAPI.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/network/RecipeDTO.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/network/RecipeService.kt
Labels: feat

#50 feat: rearranged code and fixed detekt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MainActivity.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MainViewModel.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/network/RecipeAPI.kt
  config/detekt/detekt.yml
Labels: feat

#66 fix: fixed bug in MainViewModel.kt 41 -> 43
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MainViewModel.kt
Labels: bug

#96 feat/add_drawer
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MainActivity.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/home/HomeFragment.kt
  app/src/main/res/drawable/ic_favourite_list.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/nav_header.xml
  app/src/main/res/menu/navigation_drawer_item.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feat

#101 feat: added refresh function
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/MainViewModel.kt
  app/src/main/java/com/ivanmorgillo/corsoandroid/teamc/home/RecipesRepository.kt
Labels: Refactor, feat
